### PR TITLE
Prune spec files by black/white lists

### PR DESCRIPTION
**Pull request by commaster90**
To ensure GetCapabilitySpecs service returns the filtered specs.

### CODE REVIEW

**Comment by wjwwood** [comment]
@commaster90 Thanks for the pull request.

I'll have to think carefully about this one. Can you describe what the current behavior is and how that doesn't work for you and how this patch addresses that. Can you imagine a test which should fail before this patch and succeed afterwards?

**Comment by commaster90** [comment]
The patch affects the result from this function: *capabilities.service_discovery.spec_index_from_service*.

Prior to this change, blacklisted capability interfaces were included in the returned result.
This function is used by rqt_capabilities, and therefore blacklisted interfaces were displayed in the capability graph.

We can blacklist some interface, and include a check in the file: *test_service_discovery/test_spec_index_from_service.py*.

**Comment by commaster90** [comment]
Hope the test case can clarify the issue.

**Comment by wjwwood** [comment]
Thanks, that test was exactly what I was looking for. I understand what the issue was and how it solves the problem. This looks good to merge, thanks for your patience!

**Comment by commaster90** [comment]
Thanks.

**Pull request merged**
